name: my-postgres
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: myDB
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      